static homepage
bookmebus/vshop168 pull request #81
Opened 2020-10-23 07:04 UTC by lyden29

2020-10-28 04:33 UTC, channainfo requested changes

2020-10-28 04:33 UTC, channainfo commented on app/assets/stylesheets/spree/frontend/application.scss
> +@import "spree/frontend/responsive";
Move you custom images, stylesheets and javascripts out of spree folder put it under a theme name for example if we use **vred**  as a name then it will look like this. if we don't do so next upgrade we will have to cherry pick our files since will will override the whole folder.

app/images/vred/frontend
app/stylesheets/vred/frontend
app/javascripts/vred/frontend

2020-10-28 04:33 UTC, channainfo commented on app/helpers/application_helper.rb
> +      layouts[:homepage] = 'new_layout'
Rename the following

- rename **custom_nav_bar** to **header**
- rename **custom_footer** to **footer**

move your custom files under views/vred the same way as views/spree does, then use the theme_name helper to find the appropriate view to render.

```
def theme_name
   return params[:theme].blank? ? 'vred' : 'spree'
end

```

2020-11-04 04:39 UTC, bookmebus approved these changes

2020-11-04 04:39 UTC, merged